# Generated by Django 5.0 on 2024-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Motivo do chamado',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='motive',
            options={'ordering': ['title'], 'verbose_name': 'Motivo do chamado'},
        ),
        migrations.AlterModelOptions(
            name='servicechannel',
            options={'ordering': ['title'], 'verbose_name': 'Canal de atendimento'},
        ),
    ]
