# Generated by Django 5.0 on 2024-12-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_status_options_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['title'], 'verbose_name': 'Statu'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['name'], 'verbose_name': 'Abertura de Chamado'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='motive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='tickets.motive', verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='serviceChannel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='tickets.servicechannel', verbose_name='Canal de atendimento'),
        ),
    ]
