# Generated by Django 5.0 on 2024-12-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finish',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Finalizado'),
            preserve_default=False,
        ),
    ]
