# Generated by Django 5.0 on 2024-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('rg', models.IntegerField(verbose_name='RG')),
                ('isterm', models.BooleanField(default=True, verbose_name='Termo assinado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_inactive', models.BooleanField(verbose_name='Inativo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'ordering': ['name'],
            },
        ),
    ]
