# Generated by Django 5.0 on 2024-11-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brilhaMais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedores',
            options={'ordering': ['name'], 'verbose_name': 'Vendedore'},
        ),
        migrations.RenameField(
            model_name='vendedores',
            old_name='isterm',
            new_name='is_term',
        ),
    ]
