# Generated by Django 5.0 on 2024-12-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_controle_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem 1'),
        ),
    ]
