# Generated by Django 5.0 on 2024-12-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_controle_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controle',
            name='img',
        ),
        migrations.RemoveField(
            model_name='controle',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='controle',
            name='img2',
        ),
    ]
