# Generated by Django 5.0 on 2024-12-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_controle_img_remove_controle_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem 1'),
        ),
    ]
