# Generated by Django 5.0 on 2024-12-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_cooperado_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperado',
            name='img',
        ),
    ]
