# Generated by Django 5.0 on 2024-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_cooperado_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='upload_image_book', verbose_name='Imagem 2'),
        ),
    ]
