# Generated by Django 5.0 on 2024-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_controle_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.IntegerField(default='0', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='controle',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem 2'),
        ),
    ]
