# Generated by Django 5.0 on 2024-12-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_controle_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.cooperado', verbose_name='Nome'),
        ),
    ]
