# Generated by Django 5.0 on 2024-12-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_alter_controle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controle',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.branch', verbose_name='Filial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.category', verbose_name='Departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='img',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Imagem 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='laptop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.product', verbose_name='Notebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.cooperado', verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='controle',
            name='phones',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='controls', to='products.phone', verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
