# Generated by Django 5.0 on 2024-12-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_alter_controle_branch_alter_controle_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='is_active',
        ),
    ]
